### ISSUE TITLE
Unable to ping MAC address

### ISSUE THREAD

**Issue by miken32** [svlsResearch/ha-mikrotik#18]
Attempting to try this script out, I can't get beyond the first install step:

    Are you sure the other device is configured properly? I am unable to ping MAC ...

Trying `ping count=1 <mac address>` on this box (RB2011UiAS 6.44.6) and another (CCR1036-8G-2S+ 6.44.1) I'm not able to "ping" any MAC addresses at all. The only way it works is by adding the appropriate arguments to make it do a proper ARP lookup:

    ping arp-ping=yes interface=ether2 count=1 <mac address>

Not sure why this is working differently for me. I would expect everyone to have this error, since you can't ping a MAC address...

**Comment by miken32** [comment]
Found my answer, moments later:

    /tool mac-server ping set enabled=yes

**Comment by nathanfaber** [comment]
Are you trying to pair different types of hardware together?
Did you start from a reset config? MAC ping should be enabled with defaults.

**Comment by miken32** [comment]
Yes identical hardware, but we're trying to add this to an existing config. Everything went as expected once that feature was re-enabled. Looking forward to testing the failover.

Since I've got you here, there are a couple of things could be clearer in the install instructions. In step 7, is the `scripts` directory necessary to copy over? In step 8, which router is `macA` from, and which is `macB` from? (I realize now that this A/B nomenclature is what you use for primary/backup, but new users don't know that yet.) In step 10, which router is this command run on?

I figured all this out, but would be nice to have it spelled out.

**Comment by nathanfaber** [comment]
No, you don't need to copy over the scripts directory. Did you find you had to do this?

A/B does not matter, it is your own physical decision. B can be the one you install from and primary (active), there really isn't a primary and backup.

The instructions should be comprehensive if followed, it sounds like you skipped a few because this is an existing config though. That is fine, you just might run into a few simple catches. My recommendation is to start from resets until you are comfortable with how it all works.
